name: Remove Closed Issue from Board

on:
  issues:
    types: [closed]

permissions:
  issues: write
  repository-projects: write

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Discard closed issues from board
        uses: content-queue/discard@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project: Tweets
          ignoredColumns: To Tweet,Tweeted
